# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37fbce2615ca0801d5f9212f24586b1b2af950cd5c7fa2faa4e95d93e16b485b6f9dbc8027ff9439fb1ffbcab2586a6a93fd7bdd20666341607955ae6933f8dd

test:
  secret_key_base: d2f0a2025b586eb2c4955daee2a9fb62bf6cf50894eba6ae912bdb9fa661711a2e5f495d3ff17f6e1327572c4653d7c80e346a87becf36833edb2e0434b39cc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
